### ISSUE TITLE
Rule "no-inferrable-return-types" not working here.

### ISSUE THREAD

**Issue by sandrosimas** [ibezkrovnyi/tslint-rules#1]
tslint.json
````
{
  "rules": {
    ...
    "no-inferrable-types": true,
    "no-inferrable-return-types": true,
    ...
  },
  "extends": [
    "tslint:recommended",
    "tslint-eslint-rules",
    "tslint-config-airbnb",
    "tslint-react",
    "@ibezkrovnyi/tslint-rules"
  ]
}
````
The code:
````
export function updateUser(data: any): Promise<any> {
  return Components.getLibrary().updateUser(data);
}
````
This should throw error?
I'm expecting a error, but nothing happen.

**Comment by ibezkrovnyi** [comment]
@sandrocsimas sorry for a delay, this repo is not actively maintained, as it currently works for 99% of my cases, however I will try my best in fixing this issue.

Could you please remove function's return type annotation and post here inferred return type shown by vscode (rose arrow on the screenshot below)?

Example, what I see in vscode (but I don't have your code, so typescript inferred return type as `any`):
![image](https://user-images.githubusercontent.com/1188919/41318683-6e8c66c0-6e99-11e8-9805-031f941b1448.png)

In your case you will probably see some more meaningful inferred return type.

Thanks

**Comment by sandrosimas** [comment]
Sorry @ibezkrovnyi, I don't have this code anymore.
In these cases I changed my mind and decided to always define the return type (using ````typedef````), instead of follow the rule of your library.
But if you still want to solve this issue, here is the problem I found:

In the example posted above, the following code returns a ````Promise<any>````:
````javascript
Components.getLibrary().updateUser(data)
````
The function ````updateUser```` implicitly also returns a ````Promise<any>````. As I understood of your library, in this case I shouldn't specify the return type since it implicitly returns a Promise, I'm right?
````javascript
export function updateUser(data: any): Promise<any> {
  return Components.getLibrary().updateUser(data);
}
````
If this is not the case, feel free to close the issue.

**Comment by ibezkrovnyi** [comment]
Failed to reproduce issue:

```ts
// return type for `components_getLibrary_updateUser` is `Promise<any>`
function components_getLibrary_updateUser(data: any) {
  return Promise.resolve(1 as any);
}
export function updateUser(data: any): Promise<any> {
  return components_getLibrary_updateUser(data);
}
```
![image](https://user-images.githubusercontent.com/1188919/41374844-95e061ac-6f54-11e8-931c-f73f752d6599.png)

However `no-inferred-return-types` rule [is not perfect](https://github.com/palantir/tslint/issues/695#issuecomment-367192971):
instead of full type comparison implementation simple typesAreEqual from https://github.com/ajafff/tslint-consistent-codestyle (@ajafff) is used.

So, this library (the same as `tslint`'s no-inferred-types and `tslint-consistent-codestyle`'s no-unnecessary-type-annotation rules) will think following types are different (at least it was true 4 months ago):
```ts
interface X1 {
  x: number; y: number; z: number;
}
interface X2 {
  x: number; z: number; y: number;
}
```
Usually ^ is not the case - we usually write types with fields in the same order. But...

So, I believe that it is possible you faced some edge case.

**Comment by sandrosimas** [comment]
Thanks, @ibezkrovnyi. So let's close this issue.

**Comment by ajafff** [comment]
I can second the elaboration of @ibezkrovnyi.
Comparing types isn't possible using the TypeScript API. There's still an open feature request to make this happen.

---

Another edge case I noticed while implementing `no-unnecessary-type-annotation` is recursion in type inference:

```ts
function fac(n: number): number {
  return n === 1 ? 1 : n * fac(n - 1);
}
```

If you remove the return type annotation, the compiler will complain about the circular inference. https://agentcooper.github.io/typescript-play/#code/GYVwdgxgLglg9mABMAhhAFGAXIsIC2ARgKYBOAlIgN4BQiipxUIpSSAvJ4gIyID8PRDiQAqZGkyIAtD3IBuGgF8gA

**Comment by ibezkrovnyi** [comment]
@ajafff thanks for your tslint rules - I'm using them every day in every project - they are really good!

Are you interested/can we somehow integrate `no-inferred-return-types` (or choose different name you like) into `tslint-consistent-codestyle`, so all related rules will be in one single repo?

Regarding circular inference - do you know if there is an issue opened in TS?

/spamming this issue
